#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -O3 -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -std=c++11 -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/xkmeans

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2 -std=c++11
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS)
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/xkmeans

OBJ_DEBUG = $(OBJDIR_DEBUG)/pqmath.o $(OBJDIR_DEBUG)/print2scrn.o $(OBJDIR_DEBUG)/randseed.o $(OBJDIR_RELEASE)/hartigan.o $(OBJDIR_DEBUG)/rbkmeans.o $(OBJDIR_DEBUG)/scriptparser.o $(OBJDIR_DEBUG)/seqkmeans.o $(OBJDIR_DEBUG)/timer.o $(OBJDIR_DEBUG)/vstring.o $(OBJDIR_DEBUG)/xbkmeans.o $(OBJDIR_DEBUG)/xbksums.o $(OBJDIR_DEBUG)/xtkmeans.o $(OBJDIR_DEBUG)/xtksums.o $(OBJDIR_DEBUG)/ioagent.o $(OBJDIR_DEBUG)/cleaner.o $(OBJDIR_DEBUG)/dataconvert.o $(OBJDIR_DEBUG)/evaluator.o $(OBJDIR_DEBUG)/gksums.o $(OBJDIR_DEBUG)/hardwaresetup.o $(OBJDIR_DEBUG)/abstractkmeans.o $(OBJDIR_DEBUG)/kmeans.o $(OBJDIR_DEBUG)/ksums.o $(OBJDIR_DEBUG)/lvectquant.o $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/minikmeans.o $(OBJDIR_DEBUG)/missionagent.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/pqmath.o $(OBJDIR_RELEASE)/print2scrn.o $(OBJDIR_RELEASE)/randseed.o $(OBJDIR_RELEASE)/hartigan.o $(OBJDIR_RELEASE)/rbkmeans.o $(OBJDIR_RELEASE)/scriptparser.o $(OBJDIR_RELEASE)/seqkmeans.o $(OBJDIR_RELEASE)/timer.o $(OBJDIR_RELEASE)/vstring.o $(OBJDIR_RELEASE)/xbkmeans.o $(OBJDIR_RELEASE)/xbksums.o $(OBJDIR_RELEASE)/xtkmeans.o $(OBJDIR_RELEASE)/xtksums.o $(OBJDIR_RELEASE)/ioagent.o $(OBJDIR_RELEASE)/cleaner.o $(OBJDIR_RELEASE)/dataconvert.o $(OBJDIR_RELEASE)/evaluator.o $(OBJDIR_RELEASE)/gksums.o $(OBJDIR_RELEASE)/hardwaresetup.o $(OBJDIR_RELEASE)/abstractkmeans.o $(OBJDIR_RELEASE)/kmeans.o $(OBJDIR_RELEASE)/ksums.o $(OBJDIR_RELEASE)/lvectquant.o $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/minikmeans.o $(OBJDIR_RELEASE)/missionagent.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/pqmath.o: pqmath.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c pqmath.cpp -o $(OBJDIR_DEBUG)/pqmath.o

$(OBJDIR_DEBUG)/print2scrn.o: print2scrn.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c print2scrn.cpp -o $(OBJDIR_DEBUG)/print2scrn.o

$(OBJDIR_DEBUG)/randseed.o: randseed.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c randseed.cpp -o $(OBJDIR_DEBUG)/randseed.o

$(OBJDIR_DEBUG)/rbkmeans.o: rbkmeans.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c rbkmeans.cpp -o $(OBJDIR_DEBUG)/rbkmeans.o

$(OBJDIR_DEBUG)/scriptparser.o: scriptparser.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c scriptparser.cpp -o $(OBJDIR_DEBUG)/scriptparser.o

$(OBJDIR_DEBUG)/seqkmeans.o: seqkmeans.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c seqkmeans.cpp -o $(OBJDIR_DEBUG)/seqkmeans.o

$(OBJDIR_DEBUG)/timer.o: timer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c timer.cpp -o $(OBJDIR_DEBUG)/timer.o

$(OBJDIR_DEBUG)/vstring.o: vstring.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c vstring.cpp -o $(OBJDIR_DEBUG)/vstring.o

$(OBJDIR_DEBUG)/hartigan.o: hartigan.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c hartigan.cpp -o $(OBJDIR_DEBUG)/hartigan.o

$(OBJDIR_DEBUG)/xbkmeans.o: xbkmeans.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xbkmeans.cpp -o $(OBJDIR_DEBUG)/xbkmeans.o

$(OBJDIR_DEBUG)/xbksums.o: xbksums.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xbksums.cpp -o $(OBJDIR_DEBUG)/xbksums.o

$(OBJDIR_DEBUG)/xtkmeans.o: xtkmeans.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xtkmeans.cpp -o $(OBJDIR_DEBUG)/xtkmeans.o

$(OBJDIR_DEBUG)/xtksums.o: xtksums.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c xtksums.cpp -o $(OBJDIR_DEBUG)/xtksums.o

$(OBJDIR_DEBUG)/ioagent.o: ioagent.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ioagent.cpp -o $(OBJDIR_DEBUG)/ioagent.o

$(OBJDIR_DEBUG)/cleaner.o: cleaner.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c cleaner.cpp -o $(OBJDIR_DEBUG)/cleaner.o

$(OBJDIR_DEBUG)/dataconvert.o: dataconvert.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c dataconvert.cpp -o $(OBJDIR_DEBUG)/dataconvert.o

$(OBJDIR_DEBUG)/evaluator.o: evaluator.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c evaluator.cpp -o $(OBJDIR_DEBUG)/evaluator.o

$(OBJDIR_DEBUG)/gksums.o: gksums.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c gksums.cpp -o $(OBJDIR_DEBUG)/gksums.o

$(OBJDIR_DEBUG)/hardwaresetup.o: hardwaresetup.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c hardwaresetup.cpp -o $(OBJDIR_DEBUG)/hardwaresetup.o

$(OBJDIR_DEBUG)/abstractkmeans.o: abstractkmeans.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c abstractkmeans.cpp -o $(OBJDIR_DEBUG)/abstractkmeans.o

$(OBJDIR_DEBUG)/kmeans.o: kmeans.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c kmeans.cpp -o $(OBJDIR_DEBUG)/kmeans.o

$(OBJDIR_DEBUG)/ksums.o: ksums.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ksums.cpp -o $(OBJDIR_DEBUG)/ksums.o

$(OBJDIR_DEBUG)/lvectquant.o: lvectquant.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lvectquant.cpp -o $(OBJDIR_DEBUG)/lvectquant.o

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/minikmeans.o: minikmeans.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c minikmeans.cpp -o $(OBJDIR_DEBUG)/minikmeans.o

$(OBJDIR_DEBUG)/missionagent.o: missionagent.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c missionagent.cpp -o $(OBJDIR_DEBUG)/missionagent.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/pqmath.o: pqmath.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c pqmath.cpp -o $(OBJDIR_RELEASE)/pqmath.o

$(OBJDIR_RELEASE)/print2scrn.o: print2scrn.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c print2scrn.cpp -o $(OBJDIR_RELEASE)/print2scrn.o

$(OBJDIR_RELEASE)/randseed.o: randseed.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c randseed.cpp -o $(OBJDIR_RELEASE)/randseed.o

$(OBJDIR_RELEASE)/rbkmeans.o: rbkmeans.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c rbkmeans.cpp -o $(OBJDIR_RELEASE)/rbkmeans.o

$(OBJDIR_RELEASE)/scriptparser.o: scriptparser.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c scriptparser.cpp -o $(OBJDIR_RELEASE)/scriptparser.o

$(OBJDIR_RELEASE)/seqkmeans.o: seqkmeans.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c seqkmeans.cpp -o $(OBJDIR_RELEASE)/seqkmeans.o

$(OBJDIR_RELEASE)/timer.o: timer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c timer.cpp -o $(OBJDIR_RELEASE)/timer.o

$(OBJDIR_RELEASE)/vstring.o: vstring.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c vstring.cpp -o $(OBJDIR_RELEASE)/vstring.o

$(OBJDIR_RELEASE)/hartigan.o: hartigan.cpp
	$(CXX) $(OBJDIR_RELEASE) $(OBJDIR_RELEASE) -c hartigan.cpp -o $(OBJDIR_RELEASE)/hartigan.o

$(OBJDIR_RELEASE)/xbkmeans.o: xbkmeans.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xbkmeans.cpp -o $(OBJDIR_RELEASE)/xbkmeans.o

$(OBJDIR_RELEASE)/xbksums.o: xbksums.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xbksums.cpp -o $(OBJDIR_RELEASE)/xbksums.o

$(OBJDIR_RELEASE)/xtkmeans.o: xtkmeans.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xtkmeans.cpp -o $(OBJDIR_RELEASE)/xtkmeans.o

$(OBJDIR_RELEASE)/xtksums.o: xtksums.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c xtksums.cpp -o $(OBJDIR_RELEASE)/xtksums.o

$(OBJDIR_RELEASE)/ioagent.o: ioagent.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ioagent.cpp -o $(OBJDIR_RELEASE)/ioagent.o

$(OBJDIR_RELEASE)/cleaner.o: cleaner.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c cleaner.cpp -o $(OBJDIR_RELEASE)/cleaner.o

$(OBJDIR_RELEASE)/dataconvert.o: dataconvert.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c dataconvert.cpp -o $(OBJDIR_RELEASE)/dataconvert.o

$(OBJDIR_RELEASE)/evaluator.o: evaluator.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c evaluator.cpp -o $(OBJDIR_RELEASE)/evaluator.o

$(OBJDIR_RELEASE)/gksums.o: gksums.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c gksums.cpp -o $(OBJDIR_RELEASE)/gksums.o

$(OBJDIR_RELEASE)/hardwaresetup.o: hardwaresetup.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c hardwaresetup.cpp -o $(OBJDIR_RELEASE)/hardwaresetup.o

$(OBJDIR_RELEASE)/abstractkmeans.o: abstractkmeans.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c abstractkmeans.cpp -o $(OBJDIR_RELEASE)/abstractkmeans.o

$(OBJDIR_RELEASE)/kmeans.o: kmeans.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c kmeans.cpp -o $(OBJDIR_RELEASE)/kmeans.o

$(OBJDIR_RELEASE)/ksums.o: ksums.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ksums.cpp -o $(OBJDIR_RELEASE)/ksums.o

$(OBJDIR_RELEASE)/lvectquant.o: lvectquant.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lvectquant.cpp -o $(OBJDIR_RELEASE)/lvectquant.o

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/minikmeans.o: minikmeans.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c minikmeans.cpp -o $(OBJDIR_RELEASE)/minikmeans.o

$(OBJDIR_RELEASE)/missionagent.o: missionagent.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c missionagent.cpp -o $(OBJDIR_RELEASE)/missionagent.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

